### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by timothystewart6** [khashayarzavosh/littlelink-admin#3]
Hi!  I'd love to see a docker file so that we can spin this up without configuring your local dev environment.  Happy to contribute.  I am not familiar with laravel but am with Docker.  Not sure if you've considered this and didn't want to step on your toes!

**Comment by khashayarzavosh** [comment]
hi timothy,  I am not familiar with docker :), I'm learning front-end and from now on I work Front.

Here are some things about Docker:
https://laravel.com/docs/8.x/installation#your-first-laravel-project

thank you for contribute.

**Comment by timothystewart6** [comment]
As I mentioned, I am very familiar with Docker and can add the feature but I didn't want to if you were already considering it.

**Comment by khashayarzavosh** [comment]
No, add if you like, thankful.

**Comment by VIPKaiser** [comment]
Did you guys ever do a docker for this?
