### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by Ruriko** [khashayarzavosh/littlelink-admin#5]
I installed this on Ubuntu 20.04 with php7.3 and nginx as my webserver. I get this error when I try visit my site http://bio.adoreanime.com/
```
ErrorException
Trying to get property 'home_message' of non-object (View: /var/www/bio.adoreanime.com/htdocs/littlelink-admin/resources/views/home.blade.php)
```
Any fix to this?

**Comment by khashayarzavosh** [comment]
hi, Test these:

php artisan db:seed --class="AdminSeeder"
php artisan db:seed --class="PageSeeder"
php artisan db:seed --class="ButtonSeeder"
php artisan serve

**Comment by Ruriko** [comment]
thanks that fixed it
