### ISSUE TITLE
Attempting to remove + in url but breaks other stuff

### ISSUE THREAD

**Issue by Ruriko** [khashayarzavosh/littlelink-admin#9]
I'm trying to remove the plus sign in the url that appears on the user's page so I edited web.php and sidebar.blade.php but when I did the changes it broke the login & register button as it now returns a 404 error. Are there anymore files I need to edit to fix the linking structure?

**Comment by khashayarzavosh** [comment]
I told you to look at the profiles of the medium, put any sign you want, or
write Profile/ instead of +, Probably give you a few more errors to fix.

؛)
